name: Update README with GitHub Stats

on:
  schedule:
    # Runs once every day at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitHub Stats
        run: |
          curl -o stats.svg "https://github-readme-stats.vercel.app/api?username=afiqalghazali&show_icons=true&theme=tokyonight"
          curl -o langs.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=afiqalghazali&layout=compact&theme=tokyonight"

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add stats.svg langs.svg
          git commit -m "chore: update GitHub stats"
          git push
